name: Fu
main: io.loyloy.fe.Fe
version: 0.9.2
api-version: 1.13
load: STARTUP

commands:
  fu:
    usage: /<command> <name>
    description: Checks your balance
    aliases:
      - money

softdepend:
  - Vault

permissions:
  fu.balance:
    description: Allows you to check your balance with the /fu command
    default: true
  fu.balance.other:
    description: Allows you to check other players' balances with the /fu name command
    default: true
  fu.send:
    description: Allows you to send money to other players with the /fu send name amount command
    default: true
  fu.top:
    description: Allows you to check the top 5 richest players with the /fu top command
    default: true
  fu.?:
    description: Allows you to get help with the /fu help command
    default: true
  fu.create:
    description: Allows you to create an account
  fu.remove:
    description: Allows you to remove an account
  fu.set:
    description: Allows you to set other player's balance with the /fu set name amount command
  fu.grant:
    description: Allows you grant players money with the /fu grant name amount command
  fu.deduct:
    description: Allows you to deduct money from a player with the /fu deduct name amount command
  fu.clean:
    description: Allows you to clean all accounts with the default balance with the /fu clean command
  fu.reload:
    description: Allows you to reload the configuration with the /fu reload command
  fu.notify:
    description: Allows you to receive a notification when Fu is out of date
  fu.member:
    children:
      fu.balance: true
      fu.balance.other: true
      fu.send: true
      fu.top: true
      fu.?: true
  fu.admin:
    children:
      fu.create: true
      fu.remove: true
      fu.set: true
      fu.grant: true
      fu.deduct: true
      fu.clean: true
      fu.reload: true
      fu.notify: true
  fu.*:
    children:
      fu.member: true
      fu.admin: true
